In [2]:
%matplotlib notebook
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
from disp_one import *
from load_my_data_set import *

In [3]:
# Import data
Xtrn, Ytrn, Xtst, Ytst = load_my_data_set('../data')

In [4]:
# Normalise
Xtrn = Xtrn / 255.0
Xtst = Xtst / 255.0

In [15]:
X = np.arange(10).reshape((2,5))
X

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
np.cumsum(X, axis=1)

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35]])

In [17]:
np.cumsum(X, axis=0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  7,  9, 11, 13]])

In [59]:
def comp_pca(X):
    # Input:
    # X: N * D matrix (double)
    # Output:
    # Evecs: D-by-D matrix (double) contains all eigenvectors as columns
    # NB: follow the Task 1.3 specifications on eigenvectors.
    # EVals: Eigenvalues in descending order, D x 1 vector
    # (Note that the i-th columns of Evecs should corresponds to the i-th element in EVals)

    N = len(X)

    # Mean shift the original matrix
    X_shift = X - X.mean(axis=0)

    # Covariance matrix
    # note we use 1.0, otherwise it gets cast to int and results in all 0s
    covar_m = 1.0 / (N - 1) * np.dot(X_shift.T, X_shift)

    # find the eigenvectors and eigenvalues
    # EVecs will be the principal components
    EVals, EVecs = la.eig(covar_m)

    # The first element of each eigenvector must be non-negative
    for i in range(len(EVecs[0])):
        if EVecs[0, i] < 0:
            print 'negating'
            EVecs[:, i] *= -1

    # Order eigenvalues
    idx = EVals[::-1].argsort()
    EVals = EVals[idx]

    # Order eigenvectors by the same order
    EVecs = EVecs[:, idx]

    return EVecs.astype('float64'), EVals.astype('float64')


In [60]:
evecs, evals = comp_pca(X)

negating
negating


/home/pedro-teixeira/2b/mnist-digit-learning/dice/lib/python2.7/site-packages/ipykernel_launcher.py:36: ComplexWarning: Casting complex values to real discards the imaginary part


In [61]:
evecs[0]

array([2.56494588e-02, 8.94427191e-01, 4.47213595e-01, 2.17431612e-17,
       2.17431612e-17])